<div class="wrapper | small-text--center | small-pt--large medium-pt--large large-pt--huge">
    <ul class="main-nav">
        <li class="main-nav__item"><a href="/articles/">Articles</a></li>
        <li class="main-nav__item"><a href="/tools/">Tools</a></li>
        <li class="main-nav__item"><a href="/people/">People</a></li>
        <li class="main-nav__item"><a href="/talks-and-slides/">Talks</a></li>
    </ul>
    <a class="logo unlink" href="/"><img src="{{ site.img }}/perf-rocks-logo.svg" alt="Perf.Rocks"></a>
</div>
