<div class="wrapper | small-text--center | small-pt--large medium-pt--large large-pt--huge">
    <ul class="main-nav">
        <li class="main-nav__item"><a href="/articles/" title="Articles on web performance">Articles</a></li>
        <li class="main-nav__item"><a href="/tools/" title="Web performance tools">Tools</a></li>
        <li class="main-nav__item"><a href="/people/" title="Web performance evangelists">People</a></li>
        <li class="main-nav__item"><a href="/talks-and-slides/" title="Talks on web performance">Talks</a></li>
    </ul>
    <a class="logo unlink" href="/" title="Perf Rocks: front-end performance optimization ressources"><img src="{{ site.img }}/perf-rocks-logo.svg" alt="Perf.Rocks"></a>
</div>
